### ISSUE TITLE
wikiに新しいページ作る方法分からない

### ISSUE THREAD

**Issue by Hideyasu-Yamazaki** [mdd2012/Bluemix#1]
練習を兼ねて書いてみます。
wikiページに[new wiki]的なボタン無いんですけど、新しいwikiページはどうやって作れば良いの？

**Comment by TTsurutani** [comment]
wikiはリポジトリ単位に一つ（例えばBluemix）が付いてくる、方式だと思います

**Comment by kuninet** [comment]
Wikiタブを選択して、右肩のほうの[New Page]ボタンをを押すと新規作成できます。
ボタン出ないですか??  
ちなみに、右側のサイドバーもMarkDownでリンクを箇条書きにしただけです。鉛筆マークで編集できます。  
![wiki画像](/mdd2012/Bluemix/wiki/image/wiki-1.png)

**Comment by unafi** [comment]
new Pageありました！

**Comment by kuninet** [comment]
いえーい! :+1: :smile:
あ、Closeしたのに、RESしちゃったw
